version: '3.8'

services:
  servicea:
    image: chilinhm/cbservice-image:latest
    environment:
      - ToFail=yes
    expose:
      - "80"

  serviceb:
    image: chilinhm/cbservice-image:latest
    environment:
      - ToFail=no
    expose:
      - "80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:4000"
    depends_on:
      - servicea
